export const fakeStores = [
  {
    id: 1,
    name: "Teknoloji Mağazası",
    category: "Elektronik",
    address: "İstanbul, Kadıköy",
    phone: "+90 212 555 0101",
    email: "info@teknolojimağazası.com",
    status: "Aktif",
    createdDate: "2024-01-15",
    revenue: "₺125,000",
    products: 245,
    logo: "/brendoo_logo.svg"
  },
  {
    id: 2,
    name: "Moda Butik",
    category: "Giyim",
    address: "Ankara, Çankaya",
    phone: "+90 312 555 0202",
    email: "contact@modabutik.com",
    status: "Aktif",
    createdDate: "2024-02-20",
    revenue: "₺89,500",
    products: 156,
    logo: "/logo.png"
  },
  {
    id: 3,
    name: "Kitap Dünyası",
    category: "Kitap & Kırtasiye",
    address: "İzmir, Konak",
    phone: "+90 232 555 0303",
    email: "hello@kitapdunyasi.com",
    status: "Pasif",
    createdDate: "2023-11-10",
    revenue: "₺45,200",
    products: 892,
    logo: "/abstract.png"
  },
  {
    id: 4,
    name: "Spor Merkezi",
    category: "Spor & Outdoor",
    address: "Bursa, Nilüfer",
    phone: "+90 224 555 0404",
    email: "info@spormerkezi.com",
    status: "Aktif",
    createdDate: "2024-03-05",
    revenue: "₺67,800",
    products: 78,
    logo: "/metora.png"
  },
  {
    id: 5,
    name: "Ev Dekorasyon",
    category: "Ev & Yaşam",
    address: "Antalya, Muratpaşa",
    phone: "+90 242 555 0505",
    email: "destek@evdekorasyon.com",
    status: "Aktif",
    createdDate: "2024-01-28",
    revenue: "₺156,300",
    products: 324,
    logo: "/favicon.png"
  },
  {
    id: 6,
    name: "Gourmet Market",
    category: "Gıda & İçecek",
    address: "İstanbul, Beşiktaş",
    phone: "+90 212 555 0606",
    email: "orders@gourmetmarket.com",
    status: "Aktif",
    createdDate: "2023-12-12",
    revenue: "₺234,700",
    products: 567,
    logo: "/vite.svg"
  },
  {
    id: 7,
    name: "Oyuncak Krallığı",
    category: "Oyuncak & Hobi",
    address: "Eskişehir, Odunpazarı",
    phone: "+90 222 555 0707",
    email: "info@oyuncakkralligi.com",
    status: "Pasif",
    createdDate: "2023-09-18",
    revenue: "₺78,900",
    products: 189,
    logo: "/brendoo_logo.svg"
  },
  {
    id: 8,
    name: "Sağlık Eczanesi",
    category: "Sağlık & Kozmetik",
    address: "Adana, Seyhan",
    phone: "+90 322 555 0808",
    email: "contact@saglikeczanesi.com",
    status: "Aktif",
    createdDate: "2024-02-14",
    revenue: "₺198,400",
    products: 445,
    logo: "/logo.png"
  }
];